# Change these first
owner: dpirad007 # Your GitHub organization or username, where this repository lives
repo: dionpinto-upptime # The name of this repository

sites:
  - name: Dion Pinto
    url: https://dpirad007.github.io/dionpinto/
assignees: # Users to assign downtime issues (optional)
  - dpirad007
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /dionpinto-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dionpinto-Upptime
  introTitle: "Hi I am **Dion** and this is my Upptime"
  introMessage: Upptime for my portfolio site.
  navbar:
    - title: Status
      href: /dionpinto-upptime
    - title: Portfolio
      href: https://dpirad007.github.io/dionpinto
  css: "
    :root { --body-background-color: #1b1a1a; --body-text-color: #dce2ec;
    --card-background-color: #2a2c2d;
    --nav-background-color: #1f1f1f;
    --nav-border-bottom-color: #2d2c2c;
    --nav-current-border-bottom-color: #d61212;
    --card-border-color: #2a2c2d;
    --down-border-left-color: #ff7676;
    --down-background-color: #6b1020;
    --degraded-border-left-color: #ffc36d;
    --up-border-left-color: #53e69d;
    --tag-color: #002b29;
    --tag-up-background-color: #53e69d;
    --tag-down-background-color: #ff7676;
    --tag-degraded-background-color: #ffc36d;
    --change-background-color: #ffc36d;
    --error-button-border-color: #1a46ad;
    --error-button-background-color: #3867d6;
    --error-button-color: #dce2ec;
    --submit-button-border-color: #1a46ad;
    --submit-button-background-color: #3867d6;
    --submit-button-color: #dce2ec;
    --graph-opacity: 1;
    --graph-filter: hue-rotate(34deg) saturate(164%) brightness(89%);
    }

    article.down {
    border-left: 0.4rem solid;
    }
    article.degraded {
    border-left: 0.4rem solid;
    }
    article.up {
    border-left: 0.4rem solid;
    }
    .chartjs-render-monitor {
    filter: hue-rotate(34deg) saturate(164%) brightness(89%);
    }
    "
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
